name: Bsure_devapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.0+7

environment:
  sdk: ">=3.2.3 <3.3.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  switcher_button: ^0.0.4
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  http: ^0.13.3
  cached_network_image: ^3.2.3
  lottie: ^2.1.0
  circular_profile_avatar: ^2.0.5
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.7
  expandable_text: ^2.3.0
  retrofit: ^4.0.2
  logger: ^2.0.2+1
  json_annotation: ^4.7.0
  shared_preferences: ^2.0.15
  fluttertoast: ^8.1.2
  get: ^4.6.5
  provider: ^6.0.5
  intro_slider: ^4.2.0
  smooth_page_indicator: ^1.0.0+2
  page_indicator: ^0.4.1
  share_plus: ^7.1.0
  pin_code_fields: ^8.0.1
  sms_autofill: ^2.3.0
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  coupon_uikit: ^0.2.0
  clipboard: ^0.1.3
  confetti: ^0.7.0
  path_provider: ^2.0.5
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  url_launcher: ^6.0.13
  line_awesome_flutter: ^2.0.0
  flutter_pdfview: ^1.3.1
  photo_view: ^0.14.0
  universal_platform: ^1.0.0+1
  dio: ^5.4.0
  intl: ^0.19.0
  carousel_slider: ^4.2.1
  google_fonts: ^4.0.4
  animations: ^2.0.8
  font_awesome_flutter: ^10.6.0
  flutter_hooks: ^0.20.3
  video_player: ^2.8.1
  camera: ^0.10.5+7
  gallery_saver: ^2.3.2
  razorpay_flutter: ^1.3.5
  rxdart: ^0.27.7
  freezed_annotation: ^2.4.1
  uuid: ^4.3.3
  freezed: ^2.4.6
  flutter_bloc: ^8.1.3
  rational: ^2.2.2
  accordion: ^2.6.0
  colorful_safe_area: ^0.3.0
  contacts_service: ^0.6.3
  permission_handler: ^10.3.0
  flutter_native_contact_picker: ^0.0.6








dev_dependencies:
  flutter_test:
    sdk: flutter


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1
  retrofit_generator: ^8.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.5.4


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/animations/loading.json



  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # flutter:
  #  fonts:
  #    - family: YourFontFamily
  #      fonts:
  #        - asset: assets/fonts/YourFont-Regular.ttf
  #        - asset: assets/fonts/YourFont-Bold.ttf
  #          weight: 700
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages